apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-mock
  namespace: mock
  labels:
    appname: node-app-deployment
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: node-app-pod
      component: frontend
  template:
    metadata:
      labels:
        appname: node-app-pod     # ust match selector
        component: frontend
    spec:
      containers:
        - name: node-app
          image: 272795904558.dkr.ecr.us-east-1.amazonaws.com/clo835-midterm:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /tmp/data
              name: app-mock-volume     # Fixed name to match volume below
      imagePullSecrets:
        - name: ecr-creds
      volumes:
        - name: app-mock-volume
          persistentVolumeClaim:
            claimName: app-mock-pvc
