apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-mock-pvc
  labels:
    app: app-mock
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
