apiVersion: v1
kind: Service
metadata:
  name: clo835-clusterip
  namespace: mock
spec:
  selector:
    appname: node-app-pod
    component: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: ClusterIP
